In [1]:
import numpy as np

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print(arr1)  
print(arr2)  

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((2,3),7) # 2x3 array filled with 7

array([[7, 7, 7],
       [7, 7, 7]])

In [12]:
np.eye(3) # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)

array([1, 3, 5, 7, 9])

In [14]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [34]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float64') # Explicit type

In [29]:
my_arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [33]:
arr_int = my_arr.astype(np.int32) # Convert float to int

In [31]:
arr_int

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [35]:
arr_new = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [36]:
arr_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
arr_new.shape

(4, 3)

In [37]:
reshaped = arr_new.reshape(3,4)

In [38]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
reshaped.shape

(3, 4)

In [47]:
flattened = arr_new.flatten()  # Convert 2D or 3D.. → 1D

In [45]:
flattened

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])