In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
int(flat[0])

1

In [6]:
flat[7]

np.int64(8)

In [7]:
flat[3:6]

array([4, 5, 6])

In [8]:
print(flat[1:4])  # [2 3 4] (slice from index 1 to 3)
print(flat[:3])   # [1 2 3] (first 3 elements)
print(flat[::2])  # [1 3 5] (every 2nd element)

[2 3 4]
[1 2 3]
[ 1  3  5  7  9 11]


In [9]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
a = flat[3:7]

In [11]:
a

array([4, 5, 6, 7])

In [12]:
a[2] = 66666

In [13]:
a

array([    4,     5, 66666,     7])

In [14]:
flat # Here array flat will be changed

array([    1,     2,     3,     4,     5, 66666,     7,     8,     9,
          10,    11,    12])

In [15]:
b = flat[7:11].copy()

In [16]:
b

array([ 8,  9, 10, 11])

In [17]:
b[1] = 9999

In [18]:
b

array([   8, 9999,   10,   11])

In [19]:
flat # Here flat will not be changed because of copy 

array([    1,     2,     3,     4,     5, 66666,     7,     8,     9,
          10,    11,    12])

In [20]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [21]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]
