In [1]:
import numpy as np

In [2]:
# 1) Create a 3×3 array filled with random numbers and print its shape.

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr.shape

(3, 3)

In [3]:
# 2) Convert an array of floats [1.1, 2.2, 3.3] into integers

arr = np.array([1.1, 2.2, 3.3])
int_arr = arr.astype(int)

print(int_arr)

[1 2 3]


In [4]:
# 3) Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

arr = np.array([1, 2, 3, 4, 5, 6])
idx = arr % 2 ==0
arr[idx]

array([2, 4, 6])

In [5]:
# 4) Reshape a 1D array of size 9 into a 3×3 matrix.

arr = np.array([1,2,3,4,5,6,7,8,9])
reshaped = arr.reshape(3,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# 5) Use boolean masking to filter numbers greater than 50 in an array.

arr = np.array([1,34,76,324,76,23,99,54,9])
mask = arr > 50
arr[mask]

array([ 76, 324,  76,  99,  54])