In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], # Full row is index 0
                [4, 5, 6], # Full row is index 1
                [7, 8, 9]]) # Full row is index 2

In [3]:
arr,arr.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [4]:
arr[0],arr[1],arr[2],arr[0:1],arr[0:2],arr[1:2]

(array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([[1, 2, 3]]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[4, 5, 6]]))

In [5]:
print(np.sum(arr, axis=0))  # Sum column wise when axis = 0 (ex:1+4+7)
print(np.sum(arr, axis=1))  # Sum row wise when axis = 1 (ex:1+2+3)

[12 15 18]
[ 6 15 24]


In [6]:
# Accessing an element
print(arr[1,2]),print(arr[1][2])  # Row index 1, Column index 2 → Output: 6

6
6


(None, None)

In [7]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [8]:
arr3D = np.array([
        [[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]
    ])

In [9]:
print(arr3D.shape)

(2, 2, 3)


In [10]:
print(arr3D[0, 1, 2]),print(arr3D[1, 0, 2])

print(arr3D[:, 0, :])
print(arr3D[:, 1, :]) # : stands for all

6
9
[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]


In [11]:
# Get all rows of the first column
first_col = arr[:, 1]
print(first_col) 

[2 5 8]


In [12]:
arr3D[:, 0, :] = 0 # converted to 0

In [13]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])