In [1]:
import numpy as np

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr.dtype  # To check the dtype

dtype('int64')

In [6]:
arr.astype("float")

array([1., 2., 3., 4., 5.])

In [12]:
arr2 = np.array([10, 20, 30, 40, 50], dtype="float")

In [13]:
arr2

array([10., 20., 30., 40., 50.])

In [14]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


In [15]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [16]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


In [22]:
arr3 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex')
print(arr3)

[1.+2.j 3.+4.j 5.+6.j]


In [23]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']
