In [1]:
import numpy as np

In [2]:
arr = np.array([23,53,867,12,4,75,23,6,53])

In [3]:
int(np.mean(arr))

124

In [4]:
int(np.std(arr))


263

In [5]:
np.var(arr)

np.float64(69533.55555555556)

In [6]:
np.min(arr),np.max(arr)

(np.int64(4), np.int64(867))

In [7]:
np.sum(arr),np.prod(arr)

(np.int64(1116), np.int64(27827888839200))

In [8]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(23.0)

In [9]:
np.argmin(arr) # Return the index of the minimum value in an array.

np.int64(4)

In [10]:
np.argmax(arr) # Return the index of the maximum value in an array.

np.int64(2)

In [11]:
# np.corrcoef(arr1, arr2) # Compute the correlation coefficient matrix of two arrays.

In [12]:
np.unique(arr) # Find the unique elements of an array.

array([  4,   6,  12,  23,  53,  75, 867])

In [13]:
np.diff(arr)

array([  30,  814, -855,   -8,   71,  -52,  -17,   47])

In [14]:
np.cumsum(arr) #Compute the cumulative sum of an array.

array([  23,   76,  943,  955,  959, 1034, 1057, 1063, 1116])

In [15]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.log(arr)

array([3.13549422, 3.97029191, 6.76503898, 2.48490665, 1.38629436,
       4.31748811, 3.13549422, 1.79175947, 3.97029191])

In [17]:
# np.exp(arr)